### PR TITLE
Roofing material options and tsvs updates

### PR DESCRIPTION
**Pull request by joseph-robertson**
Addresses #[issue number here].

## Pull Request Description

Expand roof material options and update related tsv files.

TODO:
- [x] Update the changelog

## Checklist

Not all may apply:

- [x] Unit tests have been added or updated
- [x] All rake tasks have been run, and pass
- [ ] Documentation has been modified appropriately
- [x] Any new options are added to `project_testing`
- [ ] `project_testing` runs without any failures
- [ ] No unexpected regression test changes
- [x] All tests are passing (green) on circleci
- [x] The [changelog](https://github.com/NREL/OpenStudio-BuildStock/blob/master/CHANGELOG.md) has been updated appropriately
- [x] This branch is up-to-date with master

For more information on how to perform these checklist items, see the documentation's [Advanced Tutorial](https://resstock.readthedocs.io/en/latest/advanced_tutorial/index.html).

### CODE REVIEW

**Comment by trynthink** [comment]
A couple questions:

* Do we need to include any modifications to Radiant Barrier.tsv?
* Do we need to update any OSWs and regenerate the corresponding OSMs?

**Comment by TobiAdekanye** [comment]
These commits look fine. However, like @trynthink said, some extra changes were implemented in the Grid Benefit Analysis branch that arent implemented here:
https://github.com/NREL/OpenStudio-BuildStock/commit/d2377e8ae06038122a75c9fea0b40ab4d84c43b4
https://github.com/NREL/OpenStudio-BuildStock/commit/9e11e93aca1a2e718d092401233500e9ab2a6710
https://github.com/NREL/OpenStudio-BuildStock/commit/c31c84ecda203b1778511ee877aa5906a2aa39c3

**Comment by joseph-robertson** [comment]
> These commits look fine. However, like @trynthink said, some extra changes were implemented in the Grid Benefit Analysis branch that arent implemented here:
> [d2377e8](https://github.com/NREL/OpenStudio-BuildStock/commit/d2377e8ae06038122a75c9fea0b40ab4d84c43b4)
> [9e11e93](https://github.com/NREL/OpenStudio-BuildStock/commit/9e11e93aca1a2e718d092401233500e9ab2a6710)
> [c31c84e](https://github.com/NREL/OpenStudio-BuildStock/commit/c31c84ecda203b1778511ee877aa5906a2aa39c3)

@TobiAdekanye So I'm a little confused. Are you implying we should be carrying thru changes related to Heating/Cooling Setpoint Apply Offset? And weather? And vacancy? From @trynthink I got the impression we only wanted changes related to roof material.

**Comment by joseph-robertson** [comment]
> A couple questions:
> 
> * Do we need to include any modifications to Radiant Barrier.tsv?
> * Do we need to update any OSWs and regenerate the corresponding OSMs?

I don't believe these changes to possible roofing materials require any modifications to Radiant Barrier.tsv.
I added some unit tests for thermal, solar, and visible absorptances. We don't need to regenerate test osms because no test osws were added/updated.

**Comment by joseph-robertson** [comment]
@trynthink @TobiAdekanye Is this ready to go?

**Comment by trynthink** [comment]
@joseph-robertson It looks good to me, though it would be good to get concurrence from @TobiAdekanye as well. Is it standard practice on this repo to merge in changes on branches as-is or to merge/rebase on master and/or squash commits before merging? I'll leave it to you to clean up or revise these commits as needed (if at all) to be consistent with expectations or standard practice on this repo.

**Review by trynthink — APPROVED** [review]

**Comment by joseph-robertson** [comment]
> @joseph-robertson It looks good to me, though it would be good to get concurrence from @TobiAdekanye as well. Is it standard practice on this repo to merge in changes on branches as-is or to merge/rebase on master and/or squash commits before merging? I'll leave it to you to clean up or revise these commits as needed (if at all) to be consistent with expectations or standard practice on this repo.

So far on this repo we've just merged in changes on branches as-is.

@TobiAdekanye does this PR look ready to go?

**Comment by ejhw** [comment]
@trynthink What is the data source for the updated roof material options? RECS? Were there any assumptions made?

**Pull request merged**
