### PR TITLE
Bugfix: Revert Insulation Unfinished Attic to #426

### PR DESCRIPTION
**Pull request by afontani**
## Pull Request Description

The PR #432, reverted changes to Insulation Unfinished Attic.tsv initially made in #426. This PR reapplies the changes to  Insulation Unfinished Attic.tsv made in #426. 
## Checklist

Not all may apply:

- [ ] Unit tests have been added or updated
- [x] All rake tasks have been run, and pass
- [ ] Documentation has been modified appropriately
- [ ] Any new options are added to `project_testing`
- [x] `project_testing` runs without any failures
- [x] No unexpected regression test changes
- [x] All tests are passing (green) on circleci
- [x] The [changelog](https://github.com/NREL/OpenStudio-BuildStock/blob/master/CHANGELOG.md) has been updated appropriately
- [x] This branch is up-to-date with master

For more information on how to perform these checklist items, see the documentation's [Advanced Tutorial](https://resstock.readthedocs.io/en/latest/advanced_tutorial/index.html).

### CODE REVIEW

**Comment by afontani** [comment]
It does not. I thought we needed to add to the CHANGELOG.md for every pull request. I can remove the commit.

**Comment by afontani** [comment]
Also, documentation updates for this fix will be added to the buildstockbatch repository.

**Comment by joseph-robertson** [comment]
> Also, documentation updates for this fix will be added to the buildstockbatch repository.

@afontani What do you mean by this?

**Comment by afontani** [comment]
> > Also, documentation updates for this fix will be added to the buildstockbatch repository.
> 
> @afontani What do you mean by this?

@joseph-robertson  Ugh. This comment doesn't make sense anymore. Sorry.  This response was for the weather files, but the documentation update is no longer any part of the pull request.

**Pull request merged**
