### PR TITLE
Update California cooling system types and efficiencies based on RASS 2009 

### PR DESCRIPTION
**Pull request by joseph-robertson**
## Pull Request Description

This pull request updates the "HVAC System Cooling.tsv" for California (Location Region = CR11) using the 2009 California Residential Appliance Saturation Study (RASS). 

### Assumptions:

- A dwelling unit cannot have a heat pump and a room air conditioner.
    - Logic in tsv: If the HVAC System Is Heat Pump dependency is Yes, then the Option=None is 1.0.
- The building cannot have both a shared cooling system and a room air conditioner. 
    - Logic in tsv: If the HVAC System Is Shared is Both Shared or Only Cooling Shared, then the Option=None is 1.0.
- RASS is from 2009 so no data exists for 2010. 2000s data is copied to 2010s vintage.
- Uses Pinchakrd et al. (Home Energy Saver) SEER and EER values for vintage years, the average values for the age range in RASS are then created. These values are then used to create the distributions for the standard equipment efficiencies.
- In the Dependency=Heating Fuel, Fuel Oil does not exist in RASS. Fuel Oil distributions are copies of Propane.
- Evaporative coolers are included in central systems.

### Housing Characteristics Modifications

- All rows where Dependency=Location Region equal to CR11 uses RASS 2009 equipment type and efficiency saturation.
- The option "Option=FIXME Room AC, EER 9.8, 20% Conditioned" was added to the "HVAC System Cooling.tsv" file to better respect the federal minimum efficiency. Only California uses this option, the rest of the U.S. remains unchanged. 

### Changes to options_lookup.tsv

- Add options for mini split heat pumps

### Data Sources

- The age of the cooling system is taken from RASS, while efficiencies are taken from M.J. Pinckard et al. 2005 Table 5 (Home Energy Saver).
- However, RASS is only to 2009 and the efficiencies in M.J. Pinckard et al. 2005 (Home Energy Saver) are documented SEER (central) and EERs (RACs) from 1970-2003.
- For newer buildings the 2008 Title 24 requires SEER 13 and EER 8.5-9.8 and 2013 Title 24 requires SEER 14 and EER 8.5-9.8 by January 2015.

## Checklist

Not all may apply:

- [ ] Unit tests have been added or updated
- [ ] All rake tasks have been run, and pass
- [ ] Documentation has been modified appropriately
- [ ] Any new options are added to `project_testing`
- [ ] `project_testing` runs without any failures
- [ ] No unexpected regression test changes
- [ ] All tests are passing (green) on circleci
- [ ] The [changelog](https://github.com/NREL/OpenStudio-BuildStock/blob/master/CHANGELOG.md) has been updated appropriately
- [ ] This branch is up-to-date with master

For more information on how to perform these checklist items, see the documentation's [Advanced Tutorial](https://resstock.readthedocs.io/en/latest/advanced_tutorial/index.html).

### CODE REVIEW

**Comment by joseph-robertson** [comment]
Comparing a 1K sample buildstock.csv (CR11):
**master**
HVAC System Cooling | Location Region
-- | --
AC, SEER 10 | 26
AC, SEER 13 | 16
AC, SEER 15 | 1
AC, SEER 8 | 3
FIXME Room AC, EER 10.7, 20% Conditioned | 8
FIXME Room AC, EER 8.5, 20% Conditioned | 3
None | 53

**ecosnap**
HVAC System Cooling | Location Region
-- | --
AC, SEER 10 | 7
AC, SEER 13 | 26
AC, SEER 15 | 11
FIXME Room AC, EER 10.7, 20% Conditioned | 10
FIXME Room AC, EER 8.5, 20% Conditioned | 4
None | 52

@afontani

**Comment by joseph-robertson** [comment]
The tsv modifications in this PR should eventually make their way into master, right?

**Comment by afontani** [comment]
Yeah, they should. Good point. We are trying to refactor the HVAC TSVs and reduce the number of them. We have not refactored the efficiency level TSVs yet but will bring it up.

**Comment by joseph-robertson** [comment]
@afontani can you update the changelog for this PR? Then I think we can get this merged into master.

**Pull request merged**
