### PR TITLE
Update to RECS 2015

### PR DESCRIPTION
**Pull request by joseph-robertson**
Addresses #323.

Companion PR: https://github.com/NREL/resstock-estimation/pull/12.

To summarize, this:
* solves for Nbr (in terms of Nocc) for:
  * sinks, showers, baths
  * range, dishwasher, clothes washer, clothes dryer
  * plug loads, large uncommon loads
* replaces plug loads equation with RECS 2015-derived

The effect is:
* nothing for anything except plug loads
* plug loads increases slightly
* plug loads ffa coefficient increases

Here's a summary of the effect for plug loads:

TYPE | NBEDS | NOCC | FFA | OLD | NEW | %INC
-- | -- | -- | -- | -- | -- | --
SFD | 0 | 0.87 | 2000 | - | 1930.552 | -
SFD | 1 | 1.46 | 2000 | 1845.3 | 2094.425 | 13.50051
SFD | 2 | 2.05 | 2000 | 2025.5 | 2258.297 | 11.49333
SFD | 3 | 2.64 | 2000 | 2205.7 | 2422.17 | 9.814118
SFD | 4 | 3.23 | 2000 | 2385.9 | 2586.042 | 8.388554
SFD | 5 | 3.82 | 2000 | 2566.1 | 2749.915 | 7.163205
SFD | 6 | 4.41 | 2000 | 2746.3 | 2913.787 | 6.09866
MF | 0 | 0.63 | 900 | - | 1434.893 | -
MF | 1 | 1.55 | 900 | 1538.95 | 1690.423 | 9.842587
MF | 2 | 2.47 | 900 | 1719.15 | 1945.953 | 13.19271
MF | 3 | 3.39 | 900 | 1899.35 | 2201.483 | 15.90715
MF | 4 | 4.31 | 900 | 2079.55 | 2457.013 | 18.15116
MF | 5 | 5.23 | 900 | 2259.75 | 2712.543 | 20.03728
MF | 6 | 6.15 | 900 | 2439.95 | 2968.073 | 21.64481

## Checklist

Not all may apply:

- [x] Unit tests have been added or updated
- [x] The `update_measures` rake task has been run
- [x] The `test:regenerate_osms` rake task has been run
- [x] Unit tests and integrity checks all pass locally
- [ ] Documentation has been modified appropriately
- [ ] Any new options are added to `project_testing`
- [ ] `project_testing` runs without any failures
- [x] No unexpected circleci regression test changes
- [x] All tests are passing (green) on circleci
- [x] This branch is up-to-date with master

For more information on how to perform these checklist items, see the documentation's [Advanced Tutorial](https://resstock.readthedocs.io/en/latest/advanced_tutorial/index.html).

### CODE REVIEW

**Comment by joseph-robertson** [comment]
@ejhw Aside from the plug loads measure, are there any other measures that need to be updated to use occupants instead of bedrooms?

**Comment by ejhw** [comment]
> @ejhw Aside from the plug loads measure, are there any other measures that need to be updated to use occupants instead of bedrooms?

Yes, we should refactor all of the equations that currently use bedrooms to use occupants instead: 
image
image
image


I think we previously discussed that we should make this change in two steps: 

1) refactor all the equations by solving these equations for Nbr and plugging the result in to the plug load and appliance equations highlighted above.
2) Then update any equations to RECS 2015 (just plug loads?).

**Comment by joseph-robertson** [comment]
Ah ok. So all equations above will get updated to be based on number of occupants (using the existing `Nocc = xNbr + y` equations), but only plug loads will be updated to RECS 2015. Is that right?

**Comment by ejhw** [comment]
> Ah ok. So all equations above will get updated to be based on number of occupants (using the existing `Nocc = xNbr + y` equations from RECS 2001), but only plug loads will be updated to RECS 2015. Is that right?

Yes, but Matt reminded me of the updated occupancy equation you derived from RECS 2015 (https://github.com/NREL/OpenStudio-BuildStock/pull/324/files#diff-1b6dcc9f5330a841e3337b24efcc49b8R1479-R1482), so we could consider updating all the equations using that relationship as part of step 2. I'm not sure if we will want to do that yet.

**Comment by joseph-robertson** [comment]
Review the branch, not individual commits; that typo has been fixed.

The old equations are there in past commits just for reference (to see before and after).

@mdahlhausen

**Comment by ejhw** [comment]
@joseph-robertson Thanks for the summary table. I'm interested to see how much of that change is due to the Nocc refactoring and how much due to RECS 2015. 

Sorry it wasn't clear before, but I was suggesting doing a PR/merge with just the Nocc refactoring first, so we could do a regression test or small run to understand impact before changing to RECS 2015. @joseph-robertson @afontani What do you think? Still worth doing that? The 10–20% increases in plug loads are pretty large, so I'd like to understand what is causing them.

**Comment by joseph-robertson** [comment]
@ejhw The plug loads increase should be completely due to RECS 2015. The Nocc refactoring doesn't change anything (I didn't change the Nocc/Nbeds relationship).

**Comment by joseph-robertson** [comment]
To clarify how the [new plug loads equation](https://github.com/NREL/OpenStudio-BuildStock/blob/master/resources/measures/ResidentialMiscPlugLoads/measure.rb#L152) was derived:
* Based on `recs2015_public_v4.csv`
* `noccupants` is `NHSLDMEM`
* `ffa` is the `sum(TOTHSQFT, TOTCSQFT)`
* `mel_ann` is `sum(KWHMICRO, KWHTVREL, KWHHUM, KWHNEC)`
  * `KWHMICRO`: Electricity usage for microwaves
  * `KWHTVREL`: Electricity usage for all televisions and related peripherals
  * `KWHHUM`: Electricity usage for humidifiers
  * `KWHNEC`: Electricity usage for other devices and purpose not elsewhere classified
  * Note: fields like ceiling fan, dehumidifier, evap cooler were excluded because we already have measures for these
* Use `sklearn`'s `linear_model.LinearRegression.fit(...)` function with the following parameters (see it [here](https://github.com/NREL/resstock-estimation/blob/master/sources/recs/2015/plug_loads/mel_ann.py#L26-L46)):
  * `X`: `noccupants`, `ffa`
  * `y`: `mel_ann`
  * `sample_weight`: `NWEIGHT`

**Pull request merged**
