### PR TITLE
Update Setpoint and Setpoint Schedule Distributions

### PR DESCRIPTION
**Pull request by aspeake**
## Pull Request Description

Updates the thermostat heating and cooling setpoint distributions (setpoint, has offset, offset magnitude, offset schedule) to be dependent on IECC climate zone instead of AIA zone.

The code used to generate these files is found here: https://github.com/NREL/resstock-estimation/blob/tsp_updates/sources/recs/2009/Setback%20Distributions.ipynb

## Checklist

Not all may apply:

- [ ] Unit tests have been added or updated
- [ ] All rake tasks have been run, and pass
- [x] Documentation has been modified appropriately
- [ ] Any new options are added to `project_testing`
- [ ] `project_testing` runs without any failures
- [ ] No unexpected regression test changes
- [x] All tests are passing (green) on circleci
- [x] The [changelog](https://github.com/NREL/OpenStudio-BuildStock/blob/master/CHANGELOG.md) has been updated appropriately
- [x] This branch is up-to-date with master

For more information on how to perform these checklist items, see the documentation's [Advanced Tutorial](https://resstock.readthedocs.io/en/latest/advanced_tutorial/index.html).

### CODE REVIEW

**Comment by aspeake** [comment]
> 
> 
> @ejhw, @aspeake: Are we introducing these changes into the [resstock-estimation](https://github.com/NREL/resstock-estimation) repo?

Eventually we want to incorporate the script into the tsv maker, but I am currently using an existing script I had on this [branch](https://github.com/NREL/resstock-estimation/tree/tsp_updates) to get the tsvs updated and merged ASAP.

**Comment by aspeake** [comment]
> 
> 
> @aspeake Thanks for the clarification. Can you add a source tag to the bottom of the TSVs? Something like:
> 
> ```
> # Source: Constructed using U.S. EIA 2009 Residential Energy Consumption Survey (RECS) microdata.
> ```

@afontani Addressed in https://github.com/NREL/OpenStudio-BuildStock/pull/468/commits/ec3cf6a7c0be9ea15de32ec91e36fc7691f380a6

**Comment by aspeake** [comment]
@afontani @ejhw RECS building type dependency has been added and setback period options were expanded (+/- 5 hour shifts), and the PR should be ready for another review.

**Comment by ejhw** [comment]
It looks like each Option bin is within "+2" not within "+/- 1". i.e., Shouldn't Option=62F represent 61-63F instead of 62-64F?

**Comment by aspeake** [comment]
> 
> 
> It looks like each Option bin is within "+2" not within "+/- 1". i.e., Shouldn't Option=62F represent 61-63F instead of 62-64F?

Our initial approach binned the setpoints into 2 degree bins, then took the nearest integer to the median value in each bin. So the bin [62 - 64) , had a median value closest to 62.

**Comment by ejhw** [comment]
> Our initial approach binned the setpoints into 2 degree bins, then took the nearest integer to the median value in each bin. So the bin [62 - 64) , had a median value closest to 62.

Gotcha, thanks for explaining.

**Comment by aspeake** [comment]
> 
> 
> Would it be relatively easy to add a sample_count (and sample_weight) column, so we know how many samples are supporting each distribution?

addressed in 312d0f463ae22d4ea17989fee08e3b29c887900d

**Comment by ejhw** [comment]
> > Would it be relatively easy to add a sample_count (and sample_weight) column, so we know how many samples are supporting each distribution?
> 
> addressed in [312d0f4](https://github.com/NREL/OpenStudio-BuildStock/commit/312d0f463ae22d4ea17989fee08e3b29c887900d)

Thanks. Some of these sample counts are lower than I'd like (e.g., in 3C). Can you pool samples from 3B and 3C to get a distribution for both? I think that fixes the worst case for me.

**Comment by ejhw** [comment]
> > > Would it be relatively easy to add a sample_count (and sample_weight) column, so we know how many samples are supporting each distribution?
> > 
> > 
> > addressed in [312d0f4](https://github.com/NREL/OpenStudio-BuildStock/commit/312d0f463ae22d4ea17989fee08e3b29c887900d)
> 
> Thanks. Some of these sample counts are lower than I'd like (e.g., in 3C). Can you pool samples from 3B and 3C to get a distribution for both? I think that fixes the worst case for me.

We all decided to not do any lumping at this point. Hopefully these distributions will be replaced by a dataset with more samples (ecobee) in the future.

**Pull request merged**
