### PR TITLE
Addresses #344, adjust timeseries csv index for DST

### PR DESCRIPTION
**Pull request by joseph-robertson**
Addresses #344.

## Pull Request Description

[description here]

## Checklist

Not all may apply:

- [ ] Unit tests have been added or updated
- [ ] All rake tasks have been run, and pass
- [ ] PAT project measures/outputs have been updated
- [ ] Documentation has been modified appropriately
- [ ] Any new options are added to `project_testing`
- [ ] `project_testing` runs without any failures
- [ ] No unexpected regression test changes
- [ ] All tests are passing (green) on circleci
- [ ] The [changelog](https://github.com/NREL/OpenStudio-BuildStock/blob/master/CHANGELOG.md) has been updated appropriately
- [ ] This branch is up-to-date with master

For more information on how to perform these checklist items, see the documentation's [Advanced Tutorial](https://resstock.readthedocs.io/en/latest/advanced_tutorial/index.html).

### CODE REVIEW

**Comment by aspeake** [comment]
A couple issues I am noticing running test cases:
- When running a sim with TMY on a leap year, there is an additional day in February, but stops at 12/30 (8760 hours). For TMY, we probably should ignore if it is a leap year and align with the weather file. This may or may not have been a result of this issue fix
- Based on the shift seen by E+, the first hour of the day (#/#/## 1:00) should be skipped at the start of DST, and the first hour of the day should be duplicated at the end of DST. 
- The `dst_end_date` is inclusive, so this day should maintain the DST shift, and the following day at midnight should go back to ST.

**Comment by joseph-robertson** [comment]
@rajeee were you going to make an additional change to this branch? something related to adding another time index column?

**Comment by rajeee** [comment]
> @rajeee were you going to make an additional change to this branch? something related to adding another time index column?

@joseph-robertson Yeah, I am adding UTC timestamp column. It will help with aggregating time-series across timezones.

**Comment by joseph-robertson** [comment]
This should be ready to go. Just need to test on buildstockbatch, but that can be done independently. Shall we merge?

**Comment by aspeake** [comment]
> 
> 
> This should be ready to go. Just need to test on buildstockbatch, but that can be done independently. Shall we merge?
> 
> @aspeake @rajeee

I'm good with it

**Comment by rajeee** [comment]
@joseph-robertson @aspeake  I did a buildstockbatch run, and the UTC timestamp column is coming along fine. So, I think, it's ready to be merged.

**Pull request merged**
