### PR TITLE
Download datapoints dependency missing from gemfile

### PR DESCRIPTION
**Pull request by joseph-robertson**
Spotted by Philip.

### CODE REVIEW

**Comment by shorowit** [comment]
Wouldn't it be better to use [OpenStudio's UnzipFile class](https://openstudio-sdk-documentation.s3.amazonaws.com/cpp/OpenStudio-2.7.1-doc/utilities/html/classopenstudio_1_1_unzip_file.html)?

**Comment by joseph-robertson** [comment]
Yeah probably. I think I copied that portion of code from one of Ry's scripts.

**Comment by joseph-robertson** [comment]
@shorowit OK how about now?

**Comment by joseph-robertson** [comment]
@shorowit If we use OpenStudio's UnzipFile class, wouldn't we have to introduce a dependency on `openstudio` in the `download_datapoints.rb` script? Do we want that?

**Comment by shorowit** [comment]
The script can easily be run via `openstudio.exe download_datapoints.rb` if it had a `require openstudio` in it, I believe. (And of course the openstudio dependency only needs to be referenced if the user chooses to call the script with the unzip argument.)

**Comment by shorowit** [comment]
If user the specifies the unzip argument, you can wrap the `require openstudio` in a begin/rescue and then show the user a nice error msg that they need to call the script with the openstudio executable.

**Comment by joseph-robertson** [comment]
How about now? I just updated the docs to instruct the user to run the script using the openstudio cli all the time. That way I could leave out the `require 'openstudio'` altogether.

**Pull request merged**
