### PR TITLE
Fix spacing error Ducts tsv

### PR DESCRIPTION
**Pull request by TobiAdekanye**
## Pull Request Description

There is a spacing error with the present Ducts.tsv. 

## Checklist

Not all may apply:

- [ ] Unit tests have been added or updated
- [ ] All rake tasks have been run, and pass
- [ ] Documentation has been modified appropriately
- [ ] Any new options are added to `project_testing`
- [ ] `project_testing` runs without any failures
- [ ] No unexpected regression test changes
- [ ] All tests are passing (green) on circleci
- [ ] The [changelog](https://github.com/NREL/OpenStudio-BuildStock/blob/master/CHANGELOG.md) has been updated appropriately
- [ ] This branch is up-to-date with master

For more information on how to perform these checklist items, see the documentation's [Advanced Tutorial](https://resstock.readthedocs.io/en/latest/advanced_tutorial/index.html).

### CODE REVIEW

**Comment by afontani** [comment]
@TobiAdekanye: Interesting. I am surprised the integrity checks didn't catch this. Good catch.

**Comment by joseph-robertson** [comment]
@TobiAdekanye Did that extra space have any repercussions on sampling?

**Comment by TobiAdekanye** [comment]
@joseph-robertson I don't think there are repercussions on sampling. However, if we want to incorporate other UQ stuff e.g. resstock probabilities, then the extra space will throw an error.

**Review by joseph-robertson — APPROVED** [review]
👍

**Review by afontani — APPROVED** [review]

**Pull request merged**
