### PR TITLE
More none no natl avg

### PR DESCRIPTION
**Pull request by afontani**
Addresses #[issue number here].

## Pull Request Description

[description here]

## Checklist

Not all may apply:

- [ ] ~Unit tests have been added or updated~
- [x] All rake tasks have been run, and pass
- [x] PAT project measures/outputs have been updated
- [ ] ~Documentation has been modified appropriately~
- [x] Any new options are added to `project_testing`
- [x] `project_testing` runs without any failures
- [x] No unexpected regression test changes
- [x] All tests are passing (green) on circleci
- [x] The [changelog](https://github.com/NREL/OpenStudio-BuildStock/blob/master/CHANGELOG.md) has been updated appropriately
- [x] This branch is up-to-date with master

For more information on how to perform these checklist items, see the documentation's [Advanced Tutorial](https://resstock.readthedocs.io/en/latest/advanced_tutorial/index.html).

### CODE REVIEW

**Comment by joseph-robertson** [comment]
@afontani are you going to do the same updates to the singlefamilydetached project as you did to the multifamily_beta one?

**Comment by afontani** [comment]
@joseph-robertson Good question. I thought eventually the singlefamilydetached project would be absorbed into multifamily_beta. I was not planning on propagating these changes to the project.

**Comment by joseph-robertson** [comment]
@afontani I think until we actually do remove the singlefamilydetached project, we will want to keep it up to date.

**Comment by afontani** [comment]
@joseph-robertson I will propagate the changes to singlefamilydetched.

**Pull request merged**
