### PR TITLE
Increase floor area diversity

### PR DESCRIPTION
**Pull request by afontani**
## Pull Request Description

**Companion PR:** [resstock-estimation #19](https://github.com/NREL/resstock-estimation/pull/19)

The purpose of this pull request is to diversify the floor area values that are simulated in ResStock. There are now two floor area bins housing characteristics, Geometry Floor Area Coarse and Geometry Floor Area Fine. These two housing characteristics are replacing the Geometry House Size housing characteristic. The Geometry Floor Area Coarse characteristics is meant to be used as a dependency for other RECS queries. The small number of bins (as before in Geometry House Size) does not slice RECS into many bins and retains reasonable sample sizes for housing characteristics dependent on Geometry Floor Area Coarse (Geometry Garage, Geometry Stories, Bedrooms, and Infiltration). The Geometry Floor Area Fine are bins based on the American Housing Survey (AHS). To maintain consistency between the two characteristics the bin sizes have been updated in Geometry Floor Area Coarse. The `total_ffa` and `unit_ffa` arguments in `options_lookup.tsv` are obtained from Geometry Floor Area Fine bin averages from RECS 2015.

### Removal of Geometry House Size
Geometry House Size has been deleted from all projects. The measure arguments are specified in the new housing characteristic Geometry Floor Area Fine. A coarser bin specification is available in the Geometry Floor Area Coarse. It is recommended that Geometry Floor Area Coarse is used when querying RECS in combination with a lot of other dependencies. The coarser bins should allow for larger sample counts when slicing the surveys.

### AHS Spatial Dependence
The American Housing Survey (AHS) has a `UNITSIZE` field in the 2017 version of the survey, which is used as floor area bins in Geometry Floor Area Fine. The benefit of using AHS for this characteristic is that we can take advantage of the top 15 Core Based Statistical Areas (CBSAs) available in AHS. The large CBSAs can have different floor areas than more rural areas. Because CBSAs are groups of counties and therefore include a lot of suburban areas as well as urban areas. The housing characteristic AHS region is a county based specification of the to 15 CBSAs and non-CBSA Census Divisions (Census Division counties minus any top 15 CBSAs counties).

### New bins for Geometry Floor Area characteristics
Previous bins for Geometry House Size in sqft:

- 0-1499
- 1500-2499
- 2500-3499
- 3500+

New bins for Geometry Floor Area from AHS UNITSIZE floor area bins in sqft:

- 0-499
- 500-749
- 750-999
- 1000-1499
- 1500-1999
- 2000-2499
- 2500-2999
- 3000-3999
- 4000+

Most of the bins from Geometry House Size align with the AHS UNITSIZE field. Exceptions are the 2500-3499 and the 3500+ bin in Geometry House Size and the 3000-3999 and 4000+ bins in AHS. To better align the floor area bins, the bins from Geometry House Size have been updated in the Geometry Floor Area Coarse housing characteristic:

New bins for Geometry Floor Area Bin in sqft:

- 0-1499
- 1500-2499
- 2500-3999
- 4000+

### Bedrooms.tsv now uses AHS 2017
Due to low sample sizes in RECS 2015, the Bedrooms.tsv now is created based on the 2017 AHS. The Bedrooms.tsv uses `BEDROOMS` field where all rooms greater or equal to 5 are mapped to 5 and all 0 bedrooms (studios) are mapped to 1.

### Options Lookup Arguments
An analysis of the square footage values in RECS 2015 was pulled together by @ekpresent. The floor area in each bin was analyzed. Distribution metrics are included for each bin (see comment below with the tables for single-family detached, single-family attached, and multifamily). 

Since RECS 2015  sample size is low, the decision was made to switch over to AHS 2013 where numeric values of the unit floor area can be used. The AHS fields used for the query is `UNITSF` for the numeric square footage and a combination of `NUNIT2` and `NUNITS` to determine the building type. For the options lookup arguments, Mobile Homes are treated as Single-Family Detached.

### Addition of Assumptions at the footer
Each housing characteristics has the option to add assumptions via and `# Assumption: ` tag below the created by and the source comments.

Not all may apply:

- [ ] Unit tests have been added or updated
- [x] All rake tasks have been run, and pass
- [ ] Documentation has been modified appropriately
- [x] Any new options are added to `project_testing`
- [x] `project_testing` runs without any failures
- [ ] No unexpected regression test changes
- [x] All tests are passing (green) on circleci
- [x] The [changelog](https://github.com/NREL/OpenStudio-BuildStock/blob/master/CHANGELOG.md) has been updated appropriately
- [x] This branch is up-to-date with master

For more information on how to perform these checklist items, see the documentation's [Advanced Tutorial](https://resstock.readthedocs.io/en/latest/advanced_tutorial/index.html).

### CODE REVIEW

**Comment by shorowit** [comment]
How about simply "Geometry Floor Area Bin" and "Geometry Floor Area"?

**Comment by afontani** [comment]
@shorowit Thanks for the input. I am open to suggestions. I recognize the naming is not great. I don't have a strong opinion either way. Maybe others can weigh in and we can get an answer by committee. 🤷‍♂️

**Comment by afontani** [comment]
Here is the analysis @ekpresent put together for RECS 2015 and the corresponding floor area values for each of the new AHS bins. We decided to use the Average of the bin (bottom value in each table) when available. RECS 2015 floor area analysis

**Comment by afontani** [comment]
Here is the floor area distributions with the gamma distribution fit parameters using `scipy.stats.gamma.fit()`
Floor area by model type

**Comment by ejhw** [comment]
> @shorowit Thanks for the input. I am open to suggestions. I recognize the naming is not great. I don't have a strong opinion either way. Maybe others can weigh in and we can get an answer by committee. 🤷‍♂️

I know we considered it previously, but upon further consideration I kinda like Scott's idea. (even though the "Fine" bins are still bins.)

**Comment by afontani** [comment]
> > @shorowit Thanks for the input. I am open to suggestions. I recognize the naming is not great. I don't have a strong opinion either way. Maybe others can weigh in and we can get an answer by committee. 🤷‍♂️
> 
> I know we considered it previously, but upon further consideration I kinda like Scott's idea. (even though the "Fine" bins are still bins.)

Not a problem.  I will make the change per below.

- Geometry Floor Area Coarse --> Geometry Floor Area Bin
- Geometry Floor Area Fine --> Geometry Floor Area

**Comment by afontani** [comment]
Here is the AHS 2013 table of option lookup values.
image

**Comment by ejhw** [comment]
> Here is the AHS 2013 table of bin average unit floor areas used to update options_lookup.tsv `total_ffa` and `unit_ffa` arguments for the residential geometry measures.

Interesting. Sample counts would be useful here too.

**Comment by afontani** [comment]
@ejhw I was literally thinking the same thing.  I updated the table in the comment above.

**Pull request merged**
