### PR TITLE
Weather file update

### PR DESCRIPTION
**Pull request by TobiAdekanye**
## Pull Request Description

Presently, to update the weather year files, we would need to make changes to the Location Weather Filename and Location Weather Year tsvs. While this approach is fine with two weather years i.e. TMY3 and AMY weather files presently, it creates a 'ballooning' effect when one begins to add more weather years as the location weather filename tsv will need the addition of 216 EPWs to its rows and columns for each AMY year. To resolve this issue, we: 

- rename all epw weather filenames such that names are consistent between all years. New location weather filename data can be found [here](https://app.box.com/s/j11qvwi13c12gorio9gp5vpmvjy1q3x1)
- delete location weather filename and location weather year as the names are now consistent between years
- update options lookup tsv by adding weather filename arguments to the location tsv
- update options lookup tsv by removing 'location weather filename' and 'location weather year' arguments

## Checklist

Not all may apply:

- [ ] Unit tests have been added or updated
- [x] All rake tasks have been run, and pass
- [ ] Documentation has been modified appropriately
- [ ] Any new options are added to `project_testing`
- [x] `project_testing` runs without any failures
- [ ] No unexpected regression test changes
- [x] All tests are passing (green) on circleci
- [x] The [changelog](https://github.com/NREL/OpenStudio-BuildStock/blob/master/CHANGELOG.md) has been updated appropriately
- [x] This branch is up-to-date with master

For more information on how to perform these checklist items, see the documentation's [Advanced Tutorial](https://resstock.readthedocs.io/en/latest/advanced_tutorial/index.html).

### CODE REVIEW

**Comment by afontani** [comment]
@TobiAdekanye  @joseph-robertson Is there a more permanent place we can put these weather files other than SharePoint?

@TobiAdekanye can you also put up the TMY3 files and the testing project files in the same directory?

**Comment by joseph-robertson** [comment]
> @TobiAdekanye @joseph-robertson Is there a more permanent place we can put these weather files other than SharePoint?
> 
> @TobiAdekanye can you also put up the TMY3 files and the testing project files in the same directory?

The files themselves? Or do you mean the documentation?

**Comment by afontani** [comment]
> > @TobiAdekanye @joseph-robertson Is there a more permanent place we can put these weather files other than SharePoint?
> > @TobiAdekanye can you also put up the TMY3 files and the testing project files in the same directory?
> 
> The files themselves? Or do you mean the documentation?

Sorry for the confusion, the files themselves.

**Comment by joseph-robertson** [comment]
> > > @TobiAdekanye @joseph-robertson Is there a more permanent place we can put these weather files other than SharePoint?
> > > @TobiAdekanye can you also put up the TMY3 files and the testing project files in the same directory?
> > 
> > 
> > The files themselves? Or do you mean the documentation?
> 
> Sorry for the confusion, the files themselves.

They're on data.nrel.gov. Is that what you mean?

**Comment by afontani** [comment]
> > > > @TobiAdekanye @joseph-robertson Is there a more permanent place we can put these weather files other than SharePoint?
> > > > @TobiAdekanye can you also put up the TMY3 files and the testing project files in the same directory?
> > > 
> > > 
> > > The files themselves? Or do you mean the documentation?
> > 
> > 
> > Sorry for the confusion, the files themselves.
> 
> They're on data.nrel.gov. Is that what you mean? For example, here is where I patched the multifamily_beta PAT project to pull from there: https://github.com/NREL/OpenStudio-BuildStock/blob/v2.2.3/project_multifamily_beta/pat.json#L20203.
> 
> @afontani

That is perfect. Thanks for clarifying @joseph-robertson.

**Comment by TobiAdekanye** [comment]
@afontani I did not recommit the options_lookup tsv, only deleted those rows i.e. location weather filename and location weather year. I am unsure how to fix this problem.

**Comment by shorowit** [comment]
Were the changes to Insulation Unfinished Attic.tsv intentional? The PR (nor changes to the CHANGELOG) have any references to it.

**Comment by afontani** [comment]
@shorowit These changes were actually made by @joseph-robertson in PR [#426](https://github.com/NREL/OpenStudio-BuildStock/pull/426). It seems that the changes were made by the "merge conflict fixes" commit (SHA: 3953ce5). It may be an artifact of a Merge commit of trying to update the `weather-file-update` branch to master, but the commit message was changed.

@TobiAdekanye can you comment on how you satisfied the merge conflicts?

image

**Comment by shorowit** [comment]
That doesn't seem right. @joseph-robertson's PR you linked to shows the Insulation Unfinished Attic.tsv gaining a new dependency (Geometry Building Type RECS), whereas this PR seems to revert that change.

**Comment by afontani** [comment]
Well, looks like I missed it during my review. I will attempt to fix this.

**Comment by afontani** [comment]
I confirmed the file was reverted to the state just before the roofing material restructure (SHA: 9c07840b2b6a3290ab458390535951b53dd9a593).

**Pull request merged**
