### PR TITLE
Remove single-family detached, PAT projects

### PR DESCRIPTION
**Pull request by joseph-robertson**
Addresses #[issue number here].

## Pull Request Description

[description here]

## Checklist

Not all may apply:

- [ ] Unit tests have been added or updated
- [ ] All rake tasks have been run, and pass
- [ ] PAT project measures/outputs have been updated
- [ ] Documentation has been modified appropriately
- [ ] Any new options are added to `project_testing`
- [ ] `project_testing` runs without any failures
- [ ] No unexpected regression test changes
- [ ] All tests are passing (green) on circleci
- [ ] The [changelog](https://github.com/NREL/OpenStudio-BuildStock/blob/master/CHANGELOG.md) has been updated appropriately
- [ ] This branch is up-to-date with master

For more information on how to perform these checklist items, see the documentation's [Advanced Tutorial](https://resstock.readthedocs.io/en/latest/advanced_tutorial/index.html).

### CODE REVIEW

**Comment by joseph-robertson** [comment]
I believe we have tagged versions of readthedocs. So clicking the docs badge could direct you to the 2.2.1 version of readthedocs.

**Comment by ejhw** [comment]
> I believe we have tagged versions of readthedocs. So clicking the docs badge could direct you to the 2.2.1 version of readthedocs.

On the [2.2.1 commit](https://github.com/NREL/OpenStudio-BuildStock/tree/4a035c1a302f70dbfc0602e7531312d4324869d2), I'm still seeing it link to `https://resstock.readthedocs.io/en/latest/?badge=latest`
image

We also link straight to the latest docs from https://resstock.nrel.gov/, but I suppose we could change that.

**Comment by joseph-robertson** [comment]
@nmerket can you create all the 2.x tag versions of readthedocs? (or give me permissions to do so myself)

**Comment by nmerket** [comment]
I just set them to build in ReadTheDocs. They should be there soon.

**Comment by ejhw** [comment]
@joseph-robertson I added a link to docs from the releases page: https://github.com/NREL/OpenStudio-BuildStock/releases/tag/v2.2.1. Let's plan to include that from now on.

@nmerket On https://resstock.nrel.gov/, can you change the "Read the documentation" button to "Access ResStock software" link to point to "https://github.com/NREL/OpenStudio-BuildStock/releases"? That way we won't have to update the docs url whenever there is a new release.

**Pull request merged**
