### PR TITLE
revert national average plug load schedule to RBSAM-derived schedule,…

### PR DESCRIPTION
**Pull request by ejhw**
… which had accidentally been changed to CA Title 24 – CASE Plug Loads and Lighting Schedule

Addresses #[issue number here].

## Pull Request Description

[description here]

## Checklist

Not all may apply:

- [ ] Unit tests have been added or updated
- [ ] All rake tasks have been run, and pass
- [ ] PAT project measures/outputs have been updated
- [ ] Documentation has been modified appropriately
- [ ] Any new options are added to `project_testing`
- [ ] `project_testing` runs without any failures
- [ ] No unexpected regression test changes
- [ ] All tests are passing (green) on circleci
- [ ] The [changelog](https://github.com/NREL/OpenStudio-BuildStock/blob/master/CHANGELOG.md) has been updated appropriately
- [ ] This branch is up-to-date with master

For more information on how to perform these checklist items, see the documentation's [Advanced Tutorial](https://resstock.readthedocs.io/en/latest/advanced_tutorial/index.html).

### CODE REVIEW

**Comment by ejhw** [comment]
Joe pointed out that we've been using the "National Average" plug load schedule in ResStock much longer than LA. I think we just never adopted RBSAM in ResStock (only as a default in the schedule.rb and in BEopt).

In case anyone's curious how these all compare:
image

So I'm going to close this PR, though we will likely switch to something closer to RBSAM in the future.

**Comment by shorowit** [comment]
It's a duck curve! 😆

**Comment by ejhw** [comment]
Elaina said the same thing :)

**Comment by afontani** [comment]
I am re-opening this PR. The plug load schedule should not be a duck curve. The schedule was accidentally updated, and therefore we should revert to our previous state. The data from ComEd also supports a different plug load schedule closer to the RBSAM schedule.

**Comment by ejhw** [comment]
@afontani Thanks for doing this. 

One correction for posterity:
> The schedule was accidentally updated, and therefore we should revert to our previous state.
The schedule was accidentally not updated to RBSAM when we did so for BEopt, so this is not a reversion, but rather a change.

**Pull request merged**
