### PR TITLE
Remove "auto" option for number of occupants

### PR DESCRIPTION
**Pull request by joseph-robertson**
Addresses #[issue number here].

## Pull Request Description

[description here]

## Checklist

Not all may apply:

- [x] Unit tests have been added or updated
- [x] All rake tasks have been run, and pass
- [ ] ~~PAT project measures/outputs have been updated~~
- [ ] ~~Documentation has been modified appropriately~~
- [ ] ~~Any new options are added to `project_testing`~~
- [ ] ~~`project_testing` runs without any failures~~
- [ ] No unexpected regression test changes
- [x] All tests are passing (green) on circleci
- [x] The [changelog](https://github.com/NREL/OpenStudio-BuildStock/blob/master/CHANGELOG.md) has been updated appropriately
- [x] This branch is up-to-date with master

For more information on how to perform these checklist items, see the documentation's [Advanced Tutorial](https://resstock.readthedocs.io/en/latest/advanced_tutorial/index.html).

### CODE REVIEW

**Comment by shorowit** [comment]
What's the reasoning behind this?

**Comment by joseph-robertson** [comment]
I'll let @ejhw take that question.

**Comment by ejhw** [comment]
@shorowit We added a [TSV for number of occupants](https://github.com/NREL/OpenStudio-BuildStock/blob/master/project_multifamily_beta/housing_characteristics/Occupants.tsv). Joe suggested that we remove the `auto` option since it is no longer being used and the use of fractional numbers of occupants will no longer be supported by the new stochastic occupancy model.

**Comment by shorowit** [comment]
It seems like there's no harm in continuing to allow someone to use it, but if you really want to remove it, I don't understand why this code isn't cleaned up more. For example, the argument should be changed from a string to a double and then you should remove all of the `valid_float?` and `to_f` stuff.

**Comment by ejhw** [comment]
Thanks @shorowit.
@joseph-robertson I say do whatever is easiest since we'll be transitioning to hpxml.

**Comment by joseph-robertson** [comment]
Let's remove Occupants=auto from the options lookup, but leave the ability to have num_occupants=auto in the measures. Sound ok?

**Pull request merged**
