### PR TITLE
Add monthly multiplier for cooking, clothes washer, clothes dryer, and dishwasher

### PR DESCRIPTION
**Pull request by rajeee**
Adds monthly multiplier for cooking schedule.

## Pull Request Description

The cooking schedule was previously (before the ResidentialScheduleGenerator was introduced) generated using weekend, weekday, and monthly multiplier schedule. Currently, they are generated using the Markov-chain by the ResidentialScheduleGenerator. This pull request adds monthly multipliers to the schedule so generated.

monthly_multiplier
The figure above shows how the monthly cooking energy changed before and after introducing this pull request; compared to the monthly multiplier used. They seem to agree pretty closely.

This strategy was also implemented for clothes washer, clothes dryer, and dishwasher.

## Checklist

Not all may apply:

- [ ] Unit tests have been added or updated
- [ ] All rake tasks have been run, and pass
- [x] Documentation has been modified appropriately
- [x] Any new options are added to `project_testing`
- [x] `project_testing` runs without any failures
- [x] No unexpected regression test changes
- [x] All tests are passing (green) on circleci
- [x] The [changelog](https://github.com/NREL/OpenStudio-BuildStock/blob/master/CHANGELOG.md) has been updated appropriately
- [x] This branch is up-to-date with master

For more information on how to perform these checklist items, see the documentation's [Advanced Tutorial](https://resstock.readthedocs.io/en/latest/advanced_tutorial/index.html).

### CODE REVIEW

**Comment by ejhw** [comment]
@rajeee  Thanks, this is great! We will actually have multipliers for Clothes Washer, Clothes Dryer, and Dishwasher as well. Can you make sure this works for those appliances as well? I'll add multiplier values to the schedule_config.yml.

**Comment by rajeee** [comment]
> @rajeee Thanks, this is great! We will actually have multipliers for Clothes Washer, Clothes Dryer, and Dishwasher as well. Can you make sure this works for those appliances as well? I'll add multiplier values to the schedule_config.yml.

@ejhw  Sure. If you could add those multipliers, I will use those in the ScheduleGenerator.

**Comment by ejhw** [comment]
@rajeee Multipliers have been added: https://github.com/NREL/OpenStudio-BuildStock/pull/504/commits/4860c0bb5936bb9fbc804a17c9966fc80206d202

**Comment by ejhw** [comment]
image

**Comment by rajeee** [comment]
@ejhw @afontani 
Multiplier added for 3 more appliances. The results below are changes found in a single building run. Scaling the appliance duration seems to work quite well. 

dishwasher_impact
cw_impact
cd_impact

**Review by afontani — APPROVED** [review]

**Pull request merged**
